// generated by github.com/schigh/slices/internal/base.go.  do not edit.
package slices

import "sort"

// Float32Slice is the alias of []float32
type Float32Slice []float32

// Value returns the aliased []float32
func (slice Float32Slice) Value() []float32 {
	return []float32(slice)
}

// IndexOf returns the first index of needle, or -1 if not found
func (slice Float32Slice) IndexOf(needle float32) int {
	for idx, n := range slice {
		if needle == n {
			return idx
		}
	}

	return NotInSlice
}

// Contains returns true if the slice contains needle
func (slice Float32Slice) Contains(needle float32) bool {
	return slice.IndexOf(needle) != NotInSlice
}

// SortAsc will sort an []float32 in ascending order
func (slice Float32Slice) SortAsc() Float32Slice {
	sort.SliceStable(slice, func(i, j int) bool {
		return slice[i] < slice[j]
	})
	return slice
}

// SortDesc will sort an []float32 in descending order
func (slice Float32Slice) SortDesc() Float32Slice {
	sort.SliceStable(slice, func(i, j int) bool {
		return slice[j] < slice[i]
	})
	return slice
}

// Reverse will reverse the order of the slice
func (slice Float32Slice) Reverse() Float32Slice {
	l := len(slice)
	for i, j := 0, l-1; i < l/2; i++ {
		slice[i], slice[j] = slice[j], slice[i]
		j--
	}

	return slice
}

// Unique filters out duplicate values
func (slice Float32Slice) Unique() Float32Slice {
	u := make([]float32, 0, len(slice))
	m := make(map[float32]bool)

	for _, i := range slice {
		if _, ok := m[i]; !ok {
			m[i] = true
			u = append(u, i)
		}
	}

	return Float32Slice(u)
}

func (slice Float32Slice) Filter(f func(float32) bool) Float32Slice {
	out := make([]float32, 0, len(slice))
	for _, i := range slice {
		if f(i) {
			out = append(out, i)
		}
	}

	return Float32Slice(out)
}
