package slices

import "sort"

/* generated by github.com/schigh/slices/base/base.go.  do not edit. */

// Float32Slice is the alias of []float32
type Float32Slice []float32

// Value returns the aliased []float32
func (slice Float32Slice) Value() []float32 {
	return []float32(slice)
}

// IndexOf returns the first index of needle, or -1 if not found
func (slice Float32Slice) IndexOf(needle float32) int {
	for i := 0; i < len(slice); i++ {
		if needle == slice[i] {
			return i
		}
	}

	return NotInSlice
}

// Contains returns true if the slice contains needle
func (slice Float32Slice) Contains(needle float32) bool {
	return slice.IndexOf(needle) != NotInSlice
}

// SortAsc will sort the slice in ascending order
func (slice Float32Slice) SortAsc() Float32Slice {
	sort.SliceStable(slice, func(i, j int) bool {
		return slice[i] < slice[j]
	})
	return slice
}

// SortDesc will sort the slice in descending order
func (slice Float32Slice) SortDesc() Float32Slice {
	sort.SliceStable(slice, func(i, j int) bool {
		return slice[j] < slice[i]
	})
	return slice
}

// Reverse will reverse the order of the slice
func (slice Float32Slice) Reverse() Float32Slice {
	l := len(slice)
	for i, j := 0, l-1; i < l/2; i++ {
		slice[i], slice[j] = slice[j], slice[i]
		j--
	}

	return slice
}

// Unique filters out duplicate float32 values
func (slice Float32Slice) Unique() Float32Slice {
	u := make([]float32, 0, len(slice))
	m := make(map[float32]bool)

	for i := 0; i < len(slice); i++ {
		if _, ok := m[slice[i]]; !ok {
			m[slice[i]] = true
			u = append(u, slice[i])
		}
	}

	return Float32Slice(u)
}

// Filter will return all float32 values that evaluate true in the user-supplied function
func (slice Float32Slice) Filter(f func(float32) bool) Float32Slice {
	out := make([]float32, 0, len(slice))
	for i := 0; i < len(slice); i++ {
		if f(slice[i]) {
			out = append(out, slice[i])
		}
	}

	return Float32Slice(out)
}

// Each will apply a function to each float32 in the slice.
// This function will iterate over the slice completely.  No
// items in the slice should be mutated by this operation.
func (slice Float32Slice) Each(f func(float32)) {
	for i := 0; i < len(slice); i++ {
		f(slice[i])
	}
}

// TryEach will apply a function to each float32 in the slice.
// If the function returns an error, the iteration will stop and return
// the index of the element that caused the function to return the error.
// The second returned value will be first error returned from the
// supplied function, and nil otherwise.
// No items in the slice should be mutated by this operation.
func (slice Float32Slice) TryEach(f func(float32) error) (int, error) {
	for i := 0; i < len(slice); i++ {
		if err := f(slice[i]); err != nil {
			return i, err
		}
	}

	return NotInSlice, nil
}

// IfEach will apply a function to each float32 in the slice.
// If the function returns false, the iteration will stop and return
// the index of the element that caused the function to return false.
// The second returned value will be true if all members of the slice
// cause the provided function to return true, and false otherwise.
// No items in the slice should be mutated by this operation.
func (slice Float32Slice) IfEach(f func(float32) bool) (int, bool) {
	for i := 0; i < len(slice); i++ {
		if !f(slice[i]) {
			return i, false
		}
	}

	return NotInSlice, true
}

// Map will apply a function to each float32 in the slice and replace the previous value
func (slice Float32Slice) Map(f func(float32) float32) {
	for i := 0; i < len(slice); i++ {
		slice[i] = f(slice[i])
	}
}
