// generated by github.com/schigh/slices/internal/base.go.  do not edit.
package slices

import "sort"

// IntSlice is the alias of []int
type IntSlice []int

// Value returns the aliased []int
func (slice IntSlice) Value() []int {
	return []int(slice)
}

// IndexOf returns the first index of needle, or -1 if not found
func (slice IntSlice) IndexOf(needle int) int {
	for idx, n := range slice {
		if needle == n {
			return idx
		}
	}

	return NotInSlice
}

// Contains returns true if the slice contains needle
func (slice IntSlice) Contains(needle int) bool {
	return slice.IndexOf(needle) != NotInSlice
}

// SortAsc will sort an []int in ascending order
func (slice IntSlice) SortAsc() IntSlice {
	sort.SliceStable(slice, func(i, j int) bool {
		return slice[i] < slice[j]
	})
	return slice
}

// SortDesc will sort an []int in descending order
func (slice IntSlice) SortDesc() IntSlice {
	sort.SliceStable(slice, func(i, j int) bool {
		return slice[j] < slice[i]
	})
	return slice
}

// Reverse will reverse the order of the slice
func (slice IntSlice) Reverse() IntSlice {
	l := len(slice)
	for i, j := 0, l-1; i < l/2; i++ {
		slice[i], slice[j] = slice[j], slice[i]
		j--
	}

	return slice
}

// TruncateZero will trim ALL the zero values off the end of the slice,
// stopping at the first non-zero value it finds
func (slice IntSlice) TruncateZero() IntSlice {
	l := len(slice)
	if l > 0 {
		for i := l-1; i >= 0; i-- {
			if slice[i] != 0 {
				return slice[:i+1]
			}
		}
		return slice[:0]
	}

	return slice
}

// Unique filters out duplicate values
func (slice IntSlice) Unique() IntSlice {
	u := make([]int, 0, len(slice))
	m := make(map[int]bool)

	for _, i := range slice {
		if _, ok := m[i]; !ok {
			m[i] = true
			u = append(u, i)
		}
	}

	return IntSlice(u)
}

func (slice IntSlice) Filter(f func(int) bool) IntSlice {
	out := make([]int, 0, len(slice))
	for _, i := range slice {
		if f(i) {
			out = append(out, i)
		}
	}

	return IntSlice(out)
}
