// generated by github.com/schigh/slices/internal/base.go.  do not edit.
package slices

import "sort"

// Int32Slice is the alias of []int32
type Int32Slice []int32

// Value returns the aliased []int32
func (slice Int32Slice) Value() []int32 {
	return []int32(slice)
}

// IndexOf returns the first index of needle, or -1 if not found
func (slice Int32Slice) IndexOf(needle int32) int {
	for idx, n := range slice {
		if needle == n {
			return idx
		}
	}

	return NotInSlice
}

// Contains returns true if the slice contains needle
func (slice Int32Slice) Contains(needle int32) bool {
	return slice.IndexOf(needle) != NotInSlice
}

// SortAsc will sort an []int32 in ascending order
func (slice Int32Slice) SortAsc() Int32Slice {
	sort.SliceStable(slice, func(i, j int) bool {
		return slice[i] < slice[j]
	})
	return slice
}

// SortDesc will sort an []int32 in descending order
func (slice Int32Slice) SortDesc() Int32Slice {
	sort.SliceStable(slice, func(i, j int) bool {
		return slice[j] < slice[i]
	})
	return slice
}

// Reverse will reverse the order of the slice
func (slice Int32Slice) Reverse() Int32Slice {
	l := len(slice)
	for i, j := 0, l-1; i < l/2; i++ {
		slice[i], slice[j] = slice[j], slice[i]
		j--
	}

	return slice
}

// TruncateZero will trim ALL the zero values off the end of the slice,
// stopping at the first non-zero value it finds
func (slice Int32Slice) TruncateZero() Int32Slice {
	l := len(slice)
	if l > 0 {
		for i := l-1; i >= 0; i-- {
			if slice[i] != 0 {
				return slice[:i+1]
			}
		}
		return slice[:0]
	}

	return slice
}

// Unique filters out duplicate values
func (slice Int32Slice) Unique() Int32Slice {
	u := make([]int32, 0, len(slice))
	m := make(map[int32]bool)

	for _, i := range slice {
		if _, ok := m[i]; !ok {
			m[i] = true
			u = append(u, i)
		}
	}

	return Int32Slice(u)
}

func (slice Int32Slice) Filter(f func(int32) bool) Int32Slice {
	out := make([]int32, 0, len(slice))
	for _, i := range slice {
		if f(i) {
			out = append(out, i)
		}
	}

	return Int32Slice(out)
}
