
package slices

import "sort"

/* generated by github.com/schigh/slices/base/base.go.  do not edit. */

// Int32Slice is the alias of []int32
type Int32Slice []int32

// Value returns the aliased []int32
func (slice Int32Slice) Value() []int32 {
	return []int32(slice)
}

// IndexOf returns the first index of needle, or -1 if not found
func (slice Int32Slice) IndexOf(needle int32) int {
	for idx, n := range slice {
		if needle == n {
			return idx
		}
	}

	return NotInSlice
}

// Contains returns true if the slice contains needle
func (slice Int32Slice) Contains(needle int32) bool {
	return slice.IndexOf(needle) != NotInSlice
}

// SortAsc will sort the slice in ascending order
func (slice Int32Slice) SortAsc() Int32Slice {
	sort.SliceStable(slice, func(i, j int) bool {
		return slice[i] < slice[j]
	})
	return slice
}

// SortDesc will sort the slice in descending order
func (slice Int32Slice) SortDesc() Int32Slice {
	sort.SliceStable(slice, func(i, j int) bool {
		return slice[j] < slice[i]
	})
	return slice
}

// Reverse will reverse the order of the slice
func (slice Int32Slice) Reverse() Int32Slice {
	l := len(slice)
	for i, j := 0, l-1; i < l/2; i++ {
		slice[i], slice[j] = slice[j], slice[i]
		j--
	}

	return slice
}

// Unique filters out duplicate int32 values
func (slice Int32Slice) Unique() Int32Slice {
	u := make([]int32, 0, len(slice))
	m := make(map[int32]bool)

	for _, v := range slice {
		if _, ok := m[v]; !ok {
			m[v] = true
			u = append(u, v)
		}
	}

	return Int32Slice(u)
}

// Filter will return all int32 values that evaluate true in the user-supplied function
func (slice Int32Slice) Filter(f func(int32) bool) Int32Slice {
	out := make([]int32, 0, len(slice))
	for _, v := range slice {
		if f(v) {
			out = append(out, v)
		}
	}

	return Int32Slice(out)
}

// Each will apply a function to each int32 in the slice.
// This should be used with data outside of the slice as it doesn't mutate it
func (slice Int32Slice) Each(f func(int32)) {
	for _, v := range slice {
		f(v)
	}
}

// Map will apply a function to each int32 in the slice and replace the previous value
func (slice Int32Slice) Map(f func(int32) int32) {
	for i, v := range slice {
		slice[i] = f(v)
	}
}
