package slices

import "sort"

/* generated by github.com/schigh/slices/base/base.go.  do not edit. */

// Int64Slice is the alias of []int64
type Int64Slice []int64

// Value returns the aliased []int64
func (slice Int64Slice) Value() []int64 {
	return []int64(slice)
}

// IndexOf returns the first index of needle, or -1 if not found
func (slice Int64Slice) IndexOf(needle int64) int {
	for i := 0; i < len(slice); i++ {
		if needle == slice[i] {
			return i
		}
	}

	return NotInSlice
}

// Contains returns true if the slice contains needle
func (slice Int64Slice) Contains(needle int64) bool {
	return slice.IndexOf(needle) != NotInSlice
}

// SortAsc will sort the slice in ascending order
func (slice Int64Slice) SortAsc() Int64Slice {
	sort.SliceStable(slice, func(i, j int) bool {
		return slice[i] < slice[j]
	})
	return slice
}

// SortDesc will sort the slice in descending order
func (slice Int64Slice) SortDesc() Int64Slice {
	sort.SliceStable(slice, func(i, j int) bool {
		return slice[j] < slice[i]
	})
	return slice
}

// Reverse will reverse the order of the slice
func (slice Int64Slice) Reverse() Int64Slice {
	l := len(slice)
	for i, j := 0, l-1; i < l/2; i++ {
		slice[i], slice[j] = slice[j], slice[i]
		j--
	}

	return slice
}

// Unique filters out duplicate int64 values
func (slice Int64Slice) Unique() Int64Slice {
	u := make([]int64, 0, len(slice))
	m := make(map[int64]bool)

	for i := 0; i < len(slice); i++ {
		if _, ok := m[slice[i]]; !ok {
			m[slice[i]] = true
			u = append(u, slice[i])
		}
	}

	return Int64Slice(u)
}

// Filter will return all int64 values that evaluate true in the user-supplied function
func (slice Int64Slice) Filter(f func(int64) bool) Int64Slice {
	out := make([]int64, 0, len(slice))
	for i := 0; i < len(slice); i++ {
		if f(slice[i]) {
			out = append(out, slice[i])
		}
	}

	return Int64Slice(out)
}

// Each will apply a function to each int64 in the slice.
// This function will iterate over the slice completely.  No
// items in the slice should be mutated by this operation.
func (slice Int64Slice) Each(f func(int64)) {
	for i := 0; i < len(slice); i++ {
		f(slice[i])
	}
}

// TryEach will apply a function to each int64 in the slice.
// If the function returns an error, the iteration will stop and return
// the index of the element that caused the function to return the error.
// The second returned value will be first error returned from the
// supplied function, and nil otherwise.
// No items in the slice should be mutated by this operation.
func (slice Int64Slice) TryEach(f func(int64) error) (int, error) {
	for i := 0; i < len(slice); i++ {
		if err := f(slice[i]); err != nil {
			return i, err
		}
	}

	return NotInSlice, nil
}

// IfEach will apply a function to each int64 in the slice.
// If the function returns false, the iteration will stop and return
// the index of the element that caused the function to return false.
// The second returned value will be true if all members of the slice
// cause the provided function to return true, and false otherwise.
// No items in the slice should be mutated by this operation.
func (slice Int64Slice) IfEach(f func(int64) bool) (int, bool) {
	for i := 0; i < len(slice); i++ {
		if !f(slice[i]) {
			return i, false
		}
	}

	return NotInSlice, true
}

// Map will apply a function to each int64 in the slice and replace the previous value
func (slice Int64Slice) Map(f func(int64) int64) {
	for i := 0; i < len(slice); i++ {
		slice[i] = f(slice[i])
	}
}
