// generated by github.com/schigh/slices/internal/base.go.  do not edit.
package slices

import "sort"

// Int64Slice is the alias of []int64
type Int64Slice []int64

// Value returns the aliased []int64
func (slice Int64Slice) Value() []int64 {
	return []int64(slice)
}

// IndexOf returns the first index of needle, or -1 if not found
func (slice Int64Slice) IndexOf(needle int64) int {
	for idx, n := range slice {
		if needle == n {
			return idx
		}
	}

	return NotInSlice
}

// Contains returns true if the slice contains needle
func (slice Int64Slice) Contains(needle int64) bool {
	return slice.IndexOf(needle) != NotInSlice
}

// SortAsc will sort an []int64 in ascending order
func (slice Int64Slice) SortAsc() Int64Slice {
	sort.SliceStable(slice, func(i, j int) bool {
		return slice[i] < slice[j]
	})
	return slice
}

// SortDesc will sort an []int64 in descending order
func (slice Int64Slice) SortDesc() Int64Slice {
	sort.SliceStable(slice, func(i, j int) bool {
		return slice[j] < slice[i]
	})
	return slice
}

// Reverse will reverse the order of the slice
func (slice Int64Slice) Reverse() Int64Slice {
	l := len(slice)
	for i, j := 0, l-1; i < l/2; i++ {
		slice[i], slice[j] = slice[j], slice[i]
		j--
	}

	return slice
}

// Unique filters out duplicate values
func (slice Int64Slice) Unique() Int64Slice {
	u := make([]int64, 0, len(slice))
	m := make(map[int64]bool)

	for _, i := range slice {
		if _, ok := m[i]; !ok {
			m[i] = true
			u = append(u, i)
		}
	}

	return Int64Slice(u)
}

func (slice Int64Slice) Filter(f func(int64) bool) Int64Slice {
	out := make([]int64, 0, len(slice))
	for _, i := range slice {
		if f(i) {
			out = append(out, i)
		}
	}

	return Int64Slice(out)
}
