/* generated by github.com/schigh/slices/internal/base.go.  do not edit. */
package slices

import "sort"

// Int8Slice is the alias of []int8
type Int8Slice []int8

// Value returns the aliased []int8
func (slice Int8Slice) Value() []int8 {
	return []int8(slice)
}

// IndexOf returns the first index of needle, or -1 if not found
func (slice Int8Slice) IndexOf(needle int8) int {
	for idx, n := range slice {
		if needle == n {
			return idx
		}
	}

	return NotInSlice
}

// Contains returns true if the slice contains needle
func (slice Int8Slice) Contains(needle int8) bool {
	return slice.IndexOf(needle) != NotInSlice
}

// SortAsc will sort the slice in ascending order
func (slice Int8Slice) SortAsc() Int8Slice {
	sort.SliceStable(slice, func(i, j int) bool {
		return slice[i] < slice[j]
	})
	return slice
}

// SortDesc will sort the slice in descending order
func (slice Int8Slice) SortDesc() Int8Slice {
	sort.SliceStable(slice, func(i, j int) bool {
		return slice[j] < slice[i]
	})
	return slice
}

// Reverse will reverse the order of the slice
func (slice Int8Slice) Reverse() Int8Slice {
	l := len(slice)
	for i, j := 0, l-1; i < l/2; i++ {
		slice[i], slice[j] = slice[j], slice[i]
		j--
	}

	return slice
}

// Unique filters out duplicate int8 values
func (slice Int8Slice) Unique() Int8Slice {
	u := make([]int8, 0, len(slice))
	m := make(map[int8]bool)

	for _, v := range slice {
		if _, ok := m[v]; !ok {
			m[v] = true
			u = append(u, v)
		}
	}

	return Int8Slice(u)
}

// Filter will return all int8 values that evaluate true in the user-supplied function
func (slice Int8Slice) Filter(f func(int8) bool) Int8Slice {
	out := make([]int8, 0, len(slice))
	for _, v := range slice {
		if f(v) {
			out = append(out, v)
		}
	}

	return Int8Slice(out)
}

// Each will apply a function to each int8 in the slice.
// This should be used with data outside of the slice as it doesn't mutate it
func (slice Int8Slice) Each(f func(int8)) {
	for _, v := range slice {
		f(v)
	}
}

// Map will apply a function to each int8 in the slice and replace the previous value
func (slice Int8Slice) Map(f func(int8) int8) {
	for i, v := range slice {
		slice[i] = f(v)
	}
}
