// generated by github.com/schigh/slices/internal/base.go.  do not edit.
package slices

import "sort"

// Int8Slice is the alias of []int8
type Int8Slice []int8

// Value returns the aliased []int8
func (slice Int8Slice) Value() []int8 {
	return []int8(slice)
}

// IndexOf returns the first index of needle, or -1 if not found
func (slice Int8Slice) IndexOf(needle int8) int {
	for idx, n := range slice {
		if needle == n {
			return idx
		}
	}

	return NotInSlice
}

// Contains returns true if the slice contains needle
func (slice Int8Slice) Contains(needle int8) bool {
	return slice.IndexOf(needle) != NotInSlice
}

// SortAsc will sort an []int8 in ascending order
func (slice Int8Slice) SortAsc() Int8Slice {
	sort.SliceStable(slice, func(i, j int) bool {
		return slice[i] < slice[j]
	})
	return slice
}

// SortDesc will sort an []int8 in descending order
func (slice Int8Slice) SortDesc() Int8Slice {
	sort.SliceStable(slice, func(i, j int) bool {
		return slice[j] < slice[i]
	})
	return slice
}

// Reverse will reverse the order of the slice
func (slice Int8Slice) Reverse() Int8Slice {
	l := len(slice)
	for i, j := 0, l-1; i < l/2; i++ {
		slice[i], slice[j] = slice[j], slice[i]
		j--
	}

	return slice
}

// TruncateZero will trim ALL the zero values off the end of the slice,
// stopping at the first non-zero value it finds
func (slice Int8Slice) TruncateZero() Int8Slice {
	l := len(slice)
	if l > 0 {
		for i := l-1; i >= 0; i-- {
			if slice[i] != 0 {
				return slice[:i+1]
			}
		}
		return slice[:0]
	}

	return slice
}

// Unique filters out duplicate values
func (slice Int8Slice) Unique() Int8Slice {
	u := make([]int8, 0, len(slice))
	m := make(map[int8]bool)

	for _, i := range slice {
		if _, ok := m[i]; !ok {
			m[i] = true
			u = append(u, i)
		}
	}

	return Int8Slice(u)
}

func (slice Int8Slice) Filter(f func(int8) bool) Int8Slice {
	out := make([]int8, 0, len(slice))
	for _, i := range slice {
		if f(i) {
			out = append(out, i)
		}
	}

	return Int8Slice(out)
}
