// generated by github.com/schigh/slices/internal/base.go.  do not edit.
package slices

import "sort"

// StringSlice is the alias of []string
type StringSlice []string

// Value returns the aliased []string
func (slice StringSlice) Value() []string {
	return []string(slice)
}

// IndexOf returns the first index of needle, or -1 if not found
func (slice StringSlice) IndexOf(needle string) int {
	for idx, n := range slice {
		if needle == n {
			return idx
		}
	}

	return NotInSlice
}

// Contains returns true if the slice contains needle
func (slice StringSlice) Contains(needle string) bool {
	return slice.IndexOf(needle) != NotInSlice
}

// SortAsc will sort an []string in ascending order
func (slice StringSlice) SortAsc() StringSlice {
	sort.SliceStable(slice, func(i, j int) bool {
		return slice[i] < slice[j]
	})
	return slice
}

// SortDesc will sort an []string in descending order
func (slice StringSlice) SortDesc() StringSlice {
	sort.SliceStable(slice, func(i, j int) bool {
		return slice[j] < slice[i]
	})
	return slice
}

// Reverse will reverse the order of the slice
func (slice StringSlice) Reverse() StringSlice {
	l := len(slice)
	for i, j := 0, l-1; i < l/2; i++ {
		slice[i], slice[j] = slice[j], slice[i]
		j--
	}

	return slice
}

// TruncateZero will trim ALL the zero values off the end of the slice,
// stopping at the first non-zero value it finds
func (slice StringSlice) TruncateZero() StringSlice {
	l := len(slice)
	if l > 0 {
		for i := l-1; i >= 0; i-- {
			if slice[i] != "" {
				return slice[:i+1]
			}
		}
		return slice[:0]
	}

	return slice
}

// Unique filters out duplicate values
func (slice StringSlice) Unique() StringSlice {
	u := make([]string, 0, len(slice))
	m := make(map[string]bool)

	for _, i := range slice {
		if _, ok := m[i]; !ok {
			m[i] = true
			u = append(u, i)
		}
	}

	return StringSlice(u)
}

func (slice StringSlice) Filter(f func(string) bool) StringSlice {
	out := make([]string, 0, len(slice))
	for _, i := range slice {
		if f(i) {
			out = append(out, i)
		}
	}

	return StringSlice(out)
}
