// generated by github.com/schigh/slices/internal/base.go.  do not edit.
package slices

import (
	"testing"
	"reflect"
	"github.com/schigh/slices/internal"
)

//region TESTS
func TestUIntPtrSlice_IndexOf(t *testing.T) {
	tests := []struct {
		name string
		slice []uintptr
		needle uintptr
		expected int
	}{
		{
			name: "only item",
			slice: []uintptr{1},
			needle: 1,
			expected: 0,
		},
		{
			name: "at index 1",
			slice: []uintptr{0,1,1},
			needle: 1,
			expected: 1,
		},
		{
			name: "missing",
			slice: []uintptr{1,2,3,4},
			needle: 5,
			expected: NotInSlice,
		},
	}
	for _, test := range tests {
		t.Run(test.name, func(t *testing.T) {
			result := UIntPtrSlice(test.slice).IndexOf(test.needle)
			if result != test.expected {
				t.Errorf("expected %d, got %d", test.expected, result)
			}
		})
	}
}

func TestUIntPtrSlice_Contains(t *testing.T) {
	tests := []struct {
		name string
		slice []uintptr
		needle uintptr
		expected bool
	}{
		{
			name: "present",
			slice: []uintptr{1,2,3,4},
			needle: 4,
			expected: true,
		},
		{
			name: "not present",
			slice: []uintptr{1,2,3,4},
			needle: 5,
			expected: false,
		},
	}
	for _, test := range tests {
		t.Run(test.name, func(t *testing.T) {
			result := UIntPtrSlice(test.slice).Contains(test.needle)
			if result != test.expected {
				t.Errorf("expected %v, got %v", test.expected, result)
			}
		})
	}
}

func TestUIntPtrSlice_SortAsc(t *testing.T) {
	tests := []struct {
		name string
		slice []uintptr
		expected []uintptr
	}{
		{
			name: "empty",
			slice: []uintptr{},
			expected: []uintptr{},
		},
		{
			name: "already sorted",
			slice: []uintptr{0,1,2,3,4,5},
			expected: []uintptr{0,1,2,3,4,5},
		},
		{
			name: "reversed",
			slice: []uintptr{5,4,3,2,1,0},
			expected: []uintptr{0,1,2,3,4,5},
		},
		{
			name: "random",
			slice: []uintptr{3,1,4,5,0,2},
			expected: []uintptr{0,1,2,3,4,5},
		},
	}
	for _, test := range tests {
		t.Run(test.name, func(t *testing.T) {
			result := UIntPtrSlice(test.slice).SortAsc().Value()
			if !reflect.DeepEqual(test.expected, result) {
				t.Errorf("expected %v, got %v", test.expected, result)
			}
		})
	}
}

func TestUIntPtrSlice_SortDesc(t *testing.T) {
	tests := []struct {
		name string
		slice []uintptr
		expected []uintptr
	}{
		{
			name: "empty",
			slice: []uintptr{},
			expected: []uintptr{},
		},
		{
			name: "already sorted",
			slice: []uintptr{5,4,3,2,1,0},
			expected: []uintptr{5,4,3,2,1,0},
		},
		{
			name: "reversed",
			slice: []uintptr{0,1,2,3,4,5},
			expected: []uintptr{5,4,3,2,1,0},
		},
		{
			name: "random",
			slice: []uintptr{3,1,4,5,0,2},
			expected: []uintptr{5,4,3,2,1,0},
		},
	}
	for _, test := range tests {
		t.Run(test.name, func(t *testing.T) {
			result := UIntPtrSlice(test.slice).SortDesc().Value()
			if !reflect.DeepEqual(test.expected, result) {
				t.Errorf("expected %v, got %v", test.expected, result)
			}
		})
	}
}

func TestUIntPtrSlice_Unique(t *testing.T) {
	tests := []struct {
		name string
		slice []uintptr
		expected []uintptr
	}{
		{
			name: "unaffected",
			slice: []uintptr{0,1,2,3,4,5},
			expected: []uintptr{0,1,2,3,4,5},
		},
		{
			name: "one extra five",
			slice: []uintptr{5,0,1,2,3,4,5},
			expected: []uintptr{5,0,1,2,3,4},
		},
		{
			name: "extras everywhere",
			slice: []uintptr{0,0,1,0,1,2,2,2,3,0,3,4,2,3,4,4,2,1,0},
			expected: []uintptr{0,1,2,3,4},
		},
	}
	for _, test := range tests {
		t.Run(test.name, func(t *testing.T) {
			result := UIntPtrSlice(test.slice).Unique().Value()
			if !reflect.DeepEqual(test.expected, result) {
				t.Errorf("expected %v, got %v", test.expected, result)
			}
		})
	}
}

func TestUIntPtrSlice_Reverse(t *testing.T) {
	tests := []struct {
		name string
		slice []uintptr
		expected []uintptr
	}{
		{
			name: "even length",
			slice: []uintptr{0,1,2,3,4,5},
			expected: []uintptr{5,4,3,2,1,0},
		},
		{
			name: "odd length",
			slice: []uintptr{0,1,2,3,4,5,6},
			expected: []uintptr{6,5,4,3,2,1,0},
		},
	}
	for _, test := range tests {
		t.Run(test.name, func(t *testing.T) {
			result := UIntPtrSlice(test.slice).Reverse().Value()
			if !reflect.DeepEqual(test.expected, result) {
				t.Errorf("expected %v, got %v", test.expected, result)
			}
		})
	}
}

func TestUIntPtrSlice_Filter(t *testing.T) {
	tests := []struct {
		name string
		slice []uintptr
		expected []uintptr
		filterFunc func(uintptr) bool
	}{
		{
			name: "gt 10",
			slice: []uintptr{1, 2, 5, 11, 13, 15},
			expected: []uintptr{11, 13, 15},
			filterFunc: func(n uintptr) bool { return n > 10 },
		},
		{
			name: "mod 3",
			slice: []uintptr{1, 2, 6, 11, 12, 15, 17},
			expected: []uintptr{6, 12, 15},
			filterFunc: func(n uintptr) bool { return n%3 == 0 },
		},
	}
	for _, test := range tests {
		t.Run(test.name, func(t *testing.T) {
			result := UIntPtrSlice(test.slice).Filter(test.filterFunc).Value()
			if !reflect.DeepEqual(test.expected, result) {
				t.Errorf("expected %v, got %v", test.expected, result)
			}
		})
	}
}

//endregion

//region BENCHMARKS

func BenchmarkUIntPtrSlice_IndexOf(b *testing.B) {
	benchmarks := []struct {
		name string
		slice []uintptr
	}{
		{
			name: "10 elements",
			slice: internal.GenUIntPtrSlice(10),
		},
		{
			name: "100 elements",
			slice: internal.GenUIntPtrSlice(100),
		},
		{
			name: "1000 elements",
			slice: internal.GenUIntPtrSlice(1000),
		},
		{
			name: "10000 elements",
			slice: internal.GenUIntPtrSlice(10000),
		},
		{
			name: "100000 elements",
			slice: internal.GenUIntPtrSlice(100000),
		},
	}
	for _, bm := range benchmarks {
		b.Run(bm.name, func(b *testing.B) {
			for i := 0; i < b.N; i++ {
				UIntPtrSlice(bm.slice).IndexOf(1)
			}
		})
	}
}

func BenchmarkUIntPtrSlice_Contains(b *testing.B) {
	benchmarks := []struct {
		name string
		slice []uintptr
	}{
		{
			name: "10 elements",
			slice: internal.GenUIntPtrSlice(10),
		},
		{
			name: "100 elements",
			slice: internal.GenUIntPtrSlice(100),
		},
		{
			name: "1000 elements",
			slice: internal.GenUIntPtrSlice(1000),
		},
		{
			name: "10000 elements",
			slice: internal.GenUIntPtrSlice(10000),
		},
		{
			name: "100000 elements",
			slice: internal.GenUIntPtrSlice(100000),
		},
	}
	for _, bm := range benchmarks {
		b.Run(bm.name, func(b *testing.B) {
			for i := 0; i < b.N; i++ {
				UIntPtrSlice(bm.slice).Contains(1)
			}
		})
	}
}

func BenchmarkUIntPtrSlice_SortAsc(b *testing.B) {
	benchmarks := []struct {
		name string
		slice []uintptr
	}{
		{
			name: "10 elements",
			slice: internal.GenUIntPtrSlice(10),
		},
		{
			name: "100 elements",
			slice: internal.GenUIntPtrSlice(100),
		},
		{
			name: "1000 elements",
			slice: internal.GenUIntPtrSlice(1000),
		},
		{
			name: "10000 elements",
			slice: internal.GenUIntPtrSlice(10000),
		},
		{
			name: "100000 elements",
			slice: internal.GenUIntPtrSlice(100000),
		},
	}
	for _, bm := range benchmarks {
		b.Run(bm.name, func(b *testing.B) {
			for i := 0; i < b.N; i++ {
				UIntPtrSlice(bm.slice).SortAsc()
			}
		})
	}
}

func BenchmarkUIntPtrSlice_SortDesc(b *testing.B) {
	benchmarks := []struct {
		name string
		slice []uintptr
	}{
		{
			name: "10 elements",
			slice: internal.GenUIntPtrSlice(10),
		},
		{
			name: "100 elements",
			slice: internal.GenUIntPtrSlice(100),
		},
		{
			name: "1000 elements",
			slice: internal.GenUIntPtrSlice(1000),
		},
		{
			name: "10000 elements",
			slice: internal.GenUIntPtrSlice(10000),
		},
		{
			name: "100000 elements",
			slice: internal.GenUIntPtrSlice(100000),
		},
	}
	for _, bm := range benchmarks {
		b.Run(bm.name, func(b *testing.B) {
			for i := 0; i < b.N; i++ {
				UIntPtrSlice(bm.slice).SortDesc()
			}
		})
	}
}

func BenchmarkUIntPtrSlice_Reverse(b *testing.B) {
	benchmarks := []struct {
		name string
		slice []uintptr
	}{
		{
			name: "10 elements",
			slice: internal.GenUIntPtrSlice(10),
		},
		{
			name: "100 elements",
			slice: internal.GenUIntPtrSlice(100),
		},
		{
			name: "1000 elements",
			slice: internal.GenUIntPtrSlice(1000),
		},
		{
			name: "10000 elements",
			slice: internal.GenUIntPtrSlice(10000),
		},
		{
			name: "100000 elements",
			slice: internal.GenUIntPtrSlice(100000),
		},
	}
	for _, bm := range benchmarks {
		b.Run(bm.name, func(b *testing.B) {
			for i := 0; i < b.N; i++ {
				UIntPtrSlice(bm.slice).Reverse()
			}
		})
	}
}
//endregion
