// generated by github.com/schigh/slices/internal/base.go.  do not edit.
package slices

import "sort"

// UIntSlice is the alias of []uint
type UIntSlice []uint

// Value returns the aliased []uint
func (slice UIntSlice) Value() []uint {
	return []uint(slice)
}

// IndexOf returns the first index of needle, or -1 if not found
func (slice UIntSlice) IndexOf(needle uint) int {
	for idx, n := range slice {
		if needle == n {
			return idx
		}
	}

	return NotInSlice
}

// Contains returns true if the slice contains needle
func (slice UIntSlice) Contains(needle uint) bool {
	return slice.IndexOf(needle) != NotInSlice
}

// SortAsc will sort an []uint in ascending order
func (slice UIntSlice) SortAsc() UIntSlice {
	sort.SliceStable(slice, func(i, j int) bool {
		return slice[i] < slice[j]
	})
	return slice
}

// SortDesc will sort an []uint in descending order
func (slice UIntSlice) SortDesc() UIntSlice {
	sort.SliceStable(slice, func(i, j int) bool {
		return slice[j] < slice[i]
	})
	return slice
}

// Reverse will reverse the order of the slice
func (slice UIntSlice) Reverse() UIntSlice {
	l := len(slice)
	for i, j := 0, l-1; i < l/2; i++ {
		slice[i], slice[j] = slice[j], slice[i]
		j--
	}

	return slice
}

// TruncateZero will trim ALL the zero values off the end of the slice,
// stopping at the first non-zero value it finds
func (slice UIntSlice) TruncateZero() UIntSlice {
	l := len(slice)
	if l > 0 {
		for i := l-1; i >= 0; i-- {
			if slice[i] != 0 {
				return slice[:i+1]
			}
		}
		return slice[:0]
	}

	return slice
}

// Unique filters out duplicate values
func (slice UIntSlice) Unique() UIntSlice {
	u := make([]uint, 0, len(slice))
	m := make(map[uint]bool)

	for _, i := range slice {
		if _, ok := m[i]; !ok {
			m[i] = true
			u = append(u, i)
		}
	}

	return UIntSlice(u)
}

func (slice UIntSlice) Filter(f func(uint) bool) UIntSlice {
	out := make([]uint, 0, len(slice))
	for _, i := range slice {
		if f(i) {
			out = append(out, i)
		}
	}

	return UIntSlice(out)
}
