// generated by github.com/schigh/slices/internal/base.go.  do not edit.
package slices

import (
	"testing"
	"reflect"
	"github.com/schigh/slices/internal"
)

//region TESTS
func TestUInt64Slice_IndexOf(t *testing.T) {
	tests := []struct {
		name string
		slice []uint64
		needle uint64
		expected int
	}{
		{
			name: "only item",
			slice: []uint64{1},
			needle: 1,
			expected: 0,
		},
		{
			name: "at index 1",
			slice: []uint64{0,1,1},
			needle: 1,
			expected: 1,
		},
		{
			name: "missing",
			slice: []uint64{1,2,3,4},
			needle: 5,
			expected: NotInSlice,
		},
	}
	for _, test := range tests {
		t.Run(test.name, func(t *testing.T) {
			result := UInt64Slice(test.slice).IndexOf(test.needle)
			if result != test.expected {
				t.Errorf("expected %d, got %d", test.expected, result)
			}
		})
	}
}

func TestUInt64Slice_Contains(t *testing.T) {
	tests := []struct {
		name string
		slice []uint64
		needle uint64
		expected bool
	}{
		{
			name: "present",
			slice: []uint64{1,2,3,4},
			needle: 4,
			expected: true,
		},
		{
			name: "not present",
			slice: []uint64{1,2,3,4},
			needle: 5,
			expected: false,
		},
	}
	for _, test := range tests {
		t.Run(test.name, func(t *testing.T) {
			result := UInt64Slice(test.slice).Contains(test.needle)
			if result != test.expected {
				t.Errorf("expected %v, got %v", test.expected, result)
			}
		})
	}
}

func TestUInt64Slice_TruncateZero(t *testing.T) {
	tests := []struct {
		name string
		slice []uint64
		expected []uint64
	}{
		{
			name: "unaffected",
			slice: []uint64{1,2,3,4,5},
			expected: []uint64{1,2,3,4,5},
		},
		{
			name: "unaffected 2",
			slice: []uint64{0,0,0,0,1},
			expected: []uint64{0,0,0,0,1},
		},
		{
			name: "all but one",
			slice: []uint64{1,0,0,0,0},
			expected: []uint64{1},
		},
		{
			name: "last one only",
			slice: []uint64{1,2,3,4,0},
			expected: []uint64{1,2,3,4},
		},
		{
			name: "empties the slice",
			slice: []uint64{0,0,0,0,0},
			expected: []uint64{},
		},
		{
			name: "empty slice",
			slice: []uint64{},
			expected: []uint64{},
		},
	}
	for _, test := range tests {
		t.Run(test.name, func(t *testing.T) {
			result := UInt64Slice(test.slice).TruncateZero().Value()
			if !reflect.DeepEqual(test.expected, result) {
				t.Errorf("expected %v, got %v", test.expected, result)
			}
		})
	}
}

func TestUInt64Slice_SortAsc(t *testing.T) {
	tests := []struct {
		name string
		slice []uint64
		expected []uint64
	}{
		{
			name: "empty",
			slice: []uint64{},
			expected: []uint64{},
		},
		{
			name: "already sorted",
			slice: []uint64{0,1,2,3,4,5},
			expected: []uint64{0,1,2,3,4,5},
		},
		{
			name: "reversed",
			slice: []uint64{5,4,3,2,1,0},
			expected: []uint64{0,1,2,3,4,5},
		},
		{
			name: "random",
			slice: []uint64{3,1,4,5,0,2},
			expected: []uint64{0,1,2,3,4,5},
		},
	}
	for _, test := range tests {
		t.Run(test.name, func(t *testing.T) {
			result := UInt64Slice(test.slice).SortAsc().Value()
			if !reflect.DeepEqual(test.expected, result) {
				t.Errorf("expected %v, got %v", test.expected, result)
			}
		})
	}
}

func TestUInt64Slice_SortDesc(t *testing.T) {
	tests := []struct {
		name string
		slice []uint64
		expected []uint64
	}{
		{
			name: "empty",
			slice: []uint64{},
			expected: []uint64{},
		},
		{
			name: "already sorted",
			slice: []uint64{5,4,3,2,1,0},
			expected: []uint64{5,4,3,2,1,0},
		},
		{
			name: "reversed",
			slice: []uint64{0,1,2,3,4,5},
			expected: []uint64{5,4,3,2,1,0},
		},
		{
			name: "random",
			slice: []uint64{3,1,4,5,0,2},
			expected: []uint64{5,4,3,2,1,0},
		},
	}
	for _, test := range tests {
		t.Run(test.name, func(t *testing.T) {
			result := UInt64Slice(test.slice).SortDesc().Value()
			if !reflect.DeepEqual(test.expected, result) {
				t.Errorf("expected %v, got %v", test.expected, result)
			}
		})
	}
}

func TestUInt64Slice_Unique(t *testing.T) {
	tests := []struct {
		name string
		slice []uint64
		expected []uint64
	}{
		{
			name: "unaffected",
			slice: []uint64{0,1,2,3,4,5},
			expected: []uint64{0,1,2,3,4,5},
		},
		{
			name: "one extra five",
			slice: []uint64{5,0,1,2,3,4,5},
			expected: []uint64{5,0,1,2,3,4},
		},
		{
			name: "extras everywhere",
			slice: []uint64{0,0,1,0,1,2,2,2,3,0,3,4,2,3,4,4,2,1,0},
			expected: []uint64{0,1,2,3,4},
		},
	}
	for _, test := range tests {
		t.Run(test.name, func(t *testing.T) {
			result := UInt64Slice(test.slice).Unique().Value()
			if !reflect.DeepEqual(test.expected, result) {
				t.Errorf("expected %v, got %v", test.expected, result)
			}
		})
	}
}

func TestUInt64Slice_Reverse(t *testing.T) {
	tests := []struct {
		name string
		slice []uint64
		expected []uint64
	}{
		{
			name: "even length",
			slice: []uint64{0,1,2,3,4,5},
			expected: []uint64{5,4,3,2,1,0},
		},
		{
			name: "odd length",
			slice: []uint64{0,1,2,3,4,5,6},
			expected: []uint64{6,5,4,3,2,1,0},
		},
	}
	for _, test := range tests {
		t.Run(test.name, func(t *testing.T) {
			result := UInt64Slice(test.slice).Reverse().Value()
			if !reflect.DeepEqual(test.expected, result) {
				t.Errorf("expected %v, got %v", test.expected, result)
			}
		})
	}
}

//endregion

//region BENCHMARKS

func BenchmarkUInt64Slice_IndexOf(b *testing.B) {
	benchmarks := []struct {
		name string
		slice []uint64
	}{
		{
			name: "10 elements",
			slice: internal.GenUInt64Slice(10),
		},
		{
			name: "100 elements",
			slice: internal.GenUInt64Slice(100),
		},
		{
			name: "1000 elements",
			slice: internal.GenUInt64Slice(1000),
		},
		{
			name: "10000 elements",
			slice: internal.GenUInt64Slice(10000),
		},
		{
			name: "100000 elements",
			slice: internal.GenUInt64Slice(100000),
		},
	}
	for _, bm := range benchmarks {
		b.Run(bm.name, func(b *testing.B) {
			for i := 0; i < b.N; i++ {
				UInt64Slice(bm.slice).IndexOf(1)
			}
		})
	}
}

func BenchmarkUInt64Slice_Contains(b *testing.B) {
	benchmarks := []struct {
		name string
		slice []uint64
	}{
		{
			name: "10 elements",
			slice: internal.GenUInt64Slice(10),
		},
		{
			name: "100 elements",
			slice: internal.GenUInt64Slice(100),
		},
		{
			name: "1000 elements",
			slice: internal.GenUInt64Slice(1000),
		},
		{
			name: "10000 elements",
			slice: internal.GenUInt64Slice(10000),
		},
		{
			name: "100000 elements",
			slice: internal.GenUInt64Slice(100000),
		},
	}
	for _, bm := range benchmarks {
		b.Run(bm.name, func(b *testing.B) {
			for i := 0; i < b.N; i++ {
				UInt64Slice(bm.slice).Contains(1)
			}
		})
	}
}

func BenchmarkUInt64Slice_SortAsc(b *testing.B) {
	benchmarks := []struct {
		name string
		slice []uint64
	}{
		{
			name: "10 elements",
			slice: internal.GenUInt64Slice(10),
		},
		{
			name: "100 elements",
			slice: internal.GenUInt64Slice(100),
		},
		{
			name: "1000 elements",
			slice: internal.GenUInt64Slice(1000),
		},
		{
			name: "10000 elements",
			slice: internal.GenUInt64Slice(10000),
		},
		{
			name: "100000 elements",
			slice: internal.GenUInt64Slice(100000),
		},
	}
	for _, bm := range benchmarks {
		b.Run(bm.name, func(b *testing.B) {
			for i := 0; i < b.N; i++ {
				UInt64Slice(bm.slice).SortAsc()
			}
		})
	}
}

func BenchmarkUInt64Slice_SortDesc(b *testing.B) {
	benchmarks := []struct {
		name string
		slice []uint64
	}{
		{
			name: "10 elements",
			slice: internal.GenUInt64Slice(10),
		},
		{
			name: "100 elements",
			slice: internal.GenUInt64Slice(100),
		},
		{
			name: "1000 elements",
			slice: internal.GenUInt64Slice(1000),
		},
		{
			name: "10000 elements",
			slice: internal.GenUInt64Slice(10000),
		},
		{
			name: "100000 elements",
			slice: internal.GenUInt64Slice(100000),
		},
	}
	for _, bm := range benchmarks {
		b.Run(bm.name, func(b *testing.B) {
			for i := 0; i < b.N; i++ {
				UInt64Slice(bm.slice).SortDesc()
			}
		})
	}
}

func BenchmarkUInt64Slice_Reverse(b *testing.B) {
	benchmarks := []struct {
		name string
		slice []uint64
	}{
		{
			name: "10 elements",
			slice: internal.GenUInt64Slice(10),
		},
		{
			name: "100 elements",
			slice: internal.GenUInt64Slice(100),
		},
		{
			name: "1000 elements",
			slice: internal.GenUInt64Slice(1000),
		},
		{
			name: "10000 elements",
			slice: internal.GenUInt64Slice(10000),
		},
		{
			name: "100000 elements",
			slice: internal.GenUInt64Slice(100000),
		},
	}
	for _, bm := range benchmarks {
		b.Run(bm.name, func(b *testing.B) {
			for i := 0; i < b.N; i++ {
				UInt64Slice(bm.slice).Reverse()
			}
		})
	}
}
//endregion
