package slices

import "sort"

/* generated by github.com/schigh/slices/base/base.go.  do not edit. */

// UInt16Slice is the alias of []uint16
type UInt16Slice []uint16

// Value returns the aliased []uint16
func (slice UInt16Slice) Value() []uint16 {
	return []uint16(slice)
}

// IndexOf returns the first index of needle, or -1 if not found
func (slice UInt16Slice) IndexOf(needle uint16) int {
	for idx, n := range slice {
		if needle == n {
			return idx
		}
	}

	return NotInSlice
}

// Contains returns true if the slice contains needle
func (slice UInt16Slice) Contains(needle uint16) bool {
	return slice.IndexOf(needle) != NotInSlice
}

// SortAsc will sort the slice in ascending order
func (slice UInt16Slice) SortAsc() UInt16Slice {
	sort.SliceStable(slice, func(i, j int) bool {
		return slice[i] < slice[j]
	})
	return slice
}

// SortDesc will sort the slice in descending order
func (slice UInt16Slice) SortDesc() UInt16Slice {
	sort.SliceStable(slice, func(i, j int) bool {
		return slice[j] < slice[i]
	})
	return slice
}

// Reverse will reverse the order of the slice
func (slice UInt16Slice) Reverse() UInt16Slice {
	l := len(slice)
	for i, j := 0, l-1; i < l/2; i++ {
		slice[i], slice[j] = slice[j], slice[i]
		j--
	}

	return slice
}

// Unique filters out duplicate uint16 values
func (slice UInt16Slice) Unique() UInt16Slice {
	u := make([]uint16, 0, len(slice))
	m := make(map[uint16]bool)

	for _, v := range slice {
		if _, ok := m[v]; !ok {
			m[v] = true
			u = append(u, v)
		}
	}

	return UInt16Slice(u)
}

// Filter will return all uint16 values that evaluate true in the user-supplied function
func (slice UInt16Slice) Filter(f func(uint16) bool) UInt16Slice {
	out := make([]uint16, 0, len(slice))
	for _, v := range slice {
		if f(v) {
			out = append(out, v)
		}
	}

	return UInt16Slice(out)
}

// Each will apply a function to each uint16 in the slice.
// This function will iterate over the slice completely.  No
// items in the slice should be mutated by this operation.
func (slice UInt16Slice) Each(f func(uint16)) {
	for _, v := range slice {
		f(v)
	}
}

// TryEach will apply a function to each uint16 in the slice.
// If the function returns an error, the iteration will stop and return
// the index of the element that caused the function to return the error.
// The second returned value will be first error returned from the
// supplied function, and nil otherwise.
// No items in the slice should be mutated by this operation.
func (slice UInt16Slice) TryEach(f func(uint16) error) (int, error) {
	for i, v := range slice {
		if err := f(v); err != nil {
			return i, err
		}
	}

	return NotInSlice, nil
}

// IfEach will apply a function to each uint16 in the slice.
// If the function returns false, the iteration will stop and return
// the index of the element that caused the function to return false.
// The second returned value will be true if all members of the slice
// cause the provided function to return true, and false otherwise.
// No items in the slice should be mutated by this operation.
func (slice UInt16Slice) IfEach(f func(uint16) bool) (int, bool) {
	for i, v := range slice {
		if !f(v) {
			return i, false
		}
	}

	return NotInSlice, true
}

// Map will apply a function to each uint16 in the slice and replace the previous value
func (slice UInt16Slice) Map(f func(uint16) uint16) {
	for i, v := range slice {
		slice[i] = f(v)
	}
}
