package slices

import "sort"

/* generated by github.com/schigh/slices/base/base.go.  do not edit. */

// UInt32Slice is the alias of []uint32
type UInt32Slice []uint32

// Value returns the aliased []uint32
func (slice UInt32Slice) Value() []uint32 {
	return []uint32(slice)
}

// IndexOf returns the first index of needle, or -1 if not found
func (slice UInt32Slice) IndexOf(needle uint32) int {
	for i := 0; i < len(slice); i++ {
		if needle == slice[i] {
			return i
		}
	}

	return NotInSlice
}

// Contains returns true if the slice contains needle
func (slice UInt32Slice) Contains(needle uint32) bool {
	return slice.IndexOf(needle) != NotInSlice
}

// SortAsc will sort the slice in ascending order
func (slice UInt32Slice) SortAsc() UInt32Slice {
	sort.SliceStable(slice, func(i, j int) bool {
		return slice[i] < slice[j]
	})
	return slice
}

// SortDesc will sort the slice in descending order
func (slice UInt32Slice) SortDesc() UInt32Slice {
	sort.SliceStable(slice, func(i, j int) bool {
		return slice[j] < slice[i]
	})
	return slice
}

// Reverse will reverse the order of the slice
func (slice UInt32Slice) Reverse() UInt32Slice {
	l := len(slice)
	for i, j := 0, l-1; i < l/2; i++ {
		slice[i], slice[j] = slice[j], slice[i]
		j--
	}

	return slice
}

// Unique filters out duplicate uint32 values
func (slice UInt32Slice) Unique() UInt32Slice {
	u := make([]uint32, 0, len(slice))
	m := make(map[uint32]bool)

	for i := 0; i < len(slice); i++ {
		if _, ok := m[slice[i]]; !ok {
			m[slice[i]] = true
			u = append(u, slice[i])
		}
	}

	return UInt32Slice(u)
}

// Filter will return all uint32 values that evaluate true in the user-supplied function
func (slice UInt32Slice) Filter(f func(uint32) bool) UInt32Slice {
	out := make([]uint32, 0, len(slice))
	for i := 0; i < len(slice); i++ {
		if f(slice[i]) {
			out = append(out, slice[i])
		}
	}

	return UInt32Slice(out)
}

// Each will apply a function to each uint32 in the slice.
// This function will iterate over the slice completely.  No
// items in the slice should be mutated by this operation.
func (slice UInt32Slice) Each(f func(uint32)) {
	for i := 0; i < len(slice); i++ {
		f(slice[i])
	}
}

// TryEach will apply a function to each uint32 in the slice.
// If the function returns an error, the iteration will stop and return
// the index of the element that caused the function to return the error.
// The second returned value will be first error returned from the
// supplied function, and nil otherwise.
// No items in the slice should be mutated by this operation.
func (slice UInt32Slice) TryEach(f func(uint32) error) (int, error) {
	for i := 0; i < len(slice); i++ {
		if err := f(slice[i]); err != nil {
			return i, err
		}
	}

	return NotInSlice, nil
}

// IfEach will apply a function to each uint32 in the slice.
// If the function returns false, the iteration will stop and return
// the index of the element that caused the function to return false.
// The second returned value will be true if all members of the slice
// cause the provided function to return true, and false otherwise.
// No items in the slice should be mutated by this operation.
func (slice UInt32Slice) IfEach(f func(uint32) bool) (int, bool) {
	for i := 0; i < len(slice); i++ {
		if !f(slice[i]) {
			return i, false
		}
	}

	return NotInSlice, true
}

// Map will apply a function to each uint32 in the slice and replace the previous value
func (slice UInt32Slice) Map(f func(uint32) uint32) {
	for i := 0; i < len(slice); i++ {
		slice[i] = f(slice[i])
	}
}

// Chunk will divide the slice of uint32 into smaller slices defined by chunk length
func (slice UInt32Slice) Chunk(size int) [][]uint32 {
	l := len(slice)
	if l == 0 || size <= 0 {
		return make([][]uint32, 0)
	}

	floor := l / size
	out := make([][]uint32, 0, floor+1)
	var k int

	for i := 0; i < floor; i++ {
		k = i*size + size
		out = append(out, slice[i*size:k])
	}
	if l > k {
		out = append(out, slice[k:])
	}

	return out
}
