// generated by github.com/schigh/slices/internal/base.go.  do not edit.
package slices

import "sort"

// UInt16Slice is the alias of []uint16
type UInt16Slice []uint16

// Value returns the aliased []uint16
func (slice UInt16Slice) Value() []uint16 {
	return []uint16(slice)
}

// IndexOf returns the first index of needle, or -1 if not found
func (slice UInt16Slice) IndexOf(needle uint16) int {
	for idx, n := range slice {
		if needle == n {
			return idx
		}
	}

	return NotInSlice
}

// Contains returns true if the slice contains needle
func (slice UInt16Slice) Contains(needle uint16) bool {
	return slice.IndexOf(needle) != NotInSlice
}

// SortAsc will sort an []uint16 in ascending order
func (slice UInt16Slice) SortAsc() UInt16Slice {
	sort.SliceStable(slice, func(i, j int) bool {
		return slice[i] < slice[j]
	})
	return slice
}

// SortDesc will sort an []uint16 in descending order
func (slice UInt16Slice) SortDesc() UInt16Slice {
	sort.SliceStable(slice, func(i, j int) bool {
		return slice[j] < slice[i]
	})
	return slice
}

// Reverse will reverse the order of the slice
func (slice UInt16Slice) Reverse() UInt16Slice {
	l := len(slice)
	for i, j := 0, l-1; i < l/2; i++ {
		slice[i], slice[j] = slice[j], slice[i]
		j--
	}

	return slice
}

// TruncateZero will trim ALL the zero values off the end of the slice,
// stopping at the first non-zero value it finds
func (slice UInt16Slice) TruncateZero() UInt16Slice {
	l := len(slice)
	if l > 0 {
		for i := l-1; i >= 0; i-- {
			if slice[i] != 0 {
				return slice[:i+1]
			}
		}
		return slice[:0]
	}

	return slice
}

// Unique filters out duplicate values
func (slice UInt16Slice) Unique() UInt16Slice {
	u := make([]uint16, 0, len(slice))
	m := make(map[uint16]bool)

	for _, i := range slice {
		if _, ok := m[i]; !ok {
			m[i] = true
			u = append(u, i)
		}
	}

	return UInt16Slice(u)
}

func (slice UInt16Slice) Filter(f func(uint16) bool) UInt16Slice {
	out := make([]uint16, 0, len(slice))
	for _, i := range slice {
		if f(i) {
			out = append(out, i)
		}
	}

	return UInt16Slice(out)
}
