/* generated by github.com/schigh/slices/internal/base.go.  do not edit. */
package slices

import "sort"

// UIntSlice is the alias of []uint
type UIntSlice []uint

// Value returns the aliased []uint
func (slice UIntSlice) Value() []uint {
	return []uint(slice)
}

// IndexOf returns the first index of needle, or -1 if not found
func (slice UIntSlice) IndexOf(needle uint) int {
	for idx, n := range slice {
		if needle == n {
			return idx
		}
	}

	return NotInSlice
}

// Contains returns true if the slice contains needle
func (slice UIntSlice) Contains(needle uint) bool {
	return slice.IndexOf(needle) != NotInSlice
}

// SortAsc will sort the slice in ascending order
func (slice UIntSlice) SortAsc() UIntSlice {
	sort.SliceStable(slice, func(i, j int) bool {
		return slice[i] < slice[j]
	})
	return slice
}

// SortDesc will sort the slice in descending order
func (slice UIntSlice) SortDesc() UIntSlice {
	sort.SliceStable(slice, func(i, j int) bool {
		return slice[j] < slice[i]
	})
	return slice
}

// Reverse will reverse the order of the slice
func (slice UIntSlice) Reverse() UIntSlice {
	l := len(slice)
	for i, j := 0, l-1; i < l/2; i++ {
		slice[i], slice[j] = slice[j], slice[i]
		j--
	}

	return slice
}

// Unique filters out duplicate uint values
func (slice UIntSlice) Unique() UIntSlice {
	u := make([]uint, 0, len(slice))
	m := make(map[uint]bool)

	for _, v := range slice {
		if _, ok := m[v]; !ok {
			m[v] = true
			u = append(u, v)
		}
	}

	return UIntSlice(u)
}

// Filter will return all uint values that evaluate true in the user-supplied function
func (slice UIntSlice) Filter(f func(uint) bool) UIntSlice {
	out := make([]uint, 0, len(slice))
	for _, v := range slice {
		if f(v) {
			out = append(out, v)
		}
	}

	return UIntSlice(out)
}

// Each will apply a function to each uint in the slice.
// This should be used with data outside of the slice as it doesn't mutate it
func (slice UIntSlice) Each(f func(uint)) {
	for _, v := range slice {
		f(v)
	}
}

// Map will apply a function to each uint in the slice and replace the previous value
func (slice UIntSlice) Map(f func(uint) uint) {
	for i, v := range slice {
		slice[i] = f(v)
	}
}
