// generated by github.com/schigh/slices/internal/base.go.  do not edit.
package slices

import "sort"

// UIntPtrSlice is the alias of []uintptr
type UIntPtrSlice []uintptr

// Value returns the aliased []uintptr
func (slice UIntPtrSlice) Value() []uintptr {
	return []uintptr(slice)
}

// IndexOf returns the first index of needle, or -1 if not found
func (slice UIntPtrSlice) IndexOf(needle uintptr) int {
	for idx, n := range slice {
		if needle == n {
			return idx
		}
	}

	return NotInSlice
}

// Contains returns true if the slice contains needle
func (slice UIntPtrSlice) Contains(needle uintptr) bool {
	return slice.IndexOf(needle) != NotInSlice
}

// SortAsc will sort the slice in ascending order
func (slice UIntPtrSlice) SortAsc() UIntPtrSlice {
	sort.SliceStable(slice, func(i, j int) bool {
		return slice[i] < slice[j]
	})
	return slice
}

// SortDesc will sort the slice in descending order
func (slice UIntPtrSlice) SortDesc() UIntPtrSlice {
	sort.SliceStable(slice, func(i, j int) bool {
		return slice[j] < slice[i]
	})
	return slice
}

// Reverse will reverse the order of the slice
func (slice UIntPtrSlice) Reverse() UIntPtrSlice {
	l := len(slice)
	for i, j := 0, l-1; i < l/2; i++ {
		slice[i], slice[j] = slice[j], slice[i]
		j--
	}

	return slice
}

// Unique filters out duplicate uintptr values
func (slice UIntPtrSlice) Unique() UIntPtrSlice {
	u := make([]uintptr, 0, len(slice))
	m := make(map[uintptr]bool)

	for _, v := range slice {
		if _, ok := m[v]; !ok {
			m[v] = true
			u = append(u, v)
		}
	}

	return UIntPtrSlice(u)
}

// Filter will return all uintptr values that evaluate true in the user-supplied function
func (slice UIntPtrSlice) Filter(f func(uintptr) bool) UIntPtrSlice {
	out := make([]uintptr, 0, len(slice))
	for _, v := range slice {
		if f(v) {
			out = append(out, v)
		}
	}

	return UIntPtrSlice(out)
}

// Each will apply a function to each uintptr in the slice.
// This should be used with data outside of the slice as it doesn't mutate it
func (slice UIntPtrSlice) Each(f func(uintptr)) {
	for _, v := range slice {
		f(v)
	}
}

// Map will apply a function to each uintptr in the slice and replace the previous value
func (slice UIntPtrSlice) Map(f func(uintptr) uintptr) {
	for i, v := range slice {
		slice[i] = f(v)
	}
}
