package examples

/* generated by slices (github.com/schigh/slices).  do not edit. */
/* gen date: Wed, 05 Sep 2018 18:06:13 -0400 */

// UserSlice aliases []User
type UserSlice []User

// Value returns the wrapped User slice
func (slice UserSlice) Value() []User {
	return []User(slice)
}

// Map applies a function to every User in the slice.  This function will mutate the slice in place
func (slice UserSlice) Map(f func(*User) *User) {
	for i := 0; i < len(slice); i++ {
		v := f(&slice[i])
		slice[i] = *v
	}
}

// Filter evaluates every element in the slice, and returns all User
// instances where the eval function returns true
func (slice UserSlice) Filter(f func(*User) bool) UserSlice {
	out := make([]User, 0, len(slice))
	for i := 0; i < len(slice); i++ {
		if f(&slice[i]) {
			out = append(out, slice[i])
		}
	}

	return UserSlice(out)
}

// Each applies a function to every User in the slice.
func (slice UserSlice) Each(f func(*User)) {
	for i := 0; i < len(slice); i++ {
		f(&slice[i])
	}
}

// TryEach applies a function to every User in the slice,
// and returns the index of the element that caused the first error, and the error itself.
// If every member of the slice returns nil, this function will return (-1, nil)
// The iteration will halt on the first error encountered and return it.
func (slice UserSlice) TryEach(f func(*User) error) (int, error) {
	for i := 0; i < len(slice); i++ {
		if err := f(&slice[i]); err != nil {
			return i, err
		}
	}

	return -1, nil
}

// IfEach applies a function to every User in the slice,
// and returns the index of the element that caused the function to return false.
// If every member of the slice evaluates to true, this function will return (-1, true)
// The iteration will halt on the first false return from the function.
func (slice UserSlice) IfEach(f func(*User) bool) (int, bool) {
	for i := 0; i < len(slice); i++ {
		if !f(&slice[i]) {
			return i, false
		}
	}

	return -1, false
}
