// generated by slices (github.com/schigh/slices).  do not edit.
// gen date: Sun, 24 Jun 2018 22:47:57 -0400

package examples

// UserSlice aliases []User
type UserSlice []User

// Value returns the wrapped User slice
func (slice UserSlice) Value() []User {
	return []User(slice)
}

// Filter evaluates every element in the slice, and returns all User 
// instances where the eval function returns true
func (slice UserSlice) Filter(f func(User) bool) UserSlice {
	out := make([]User, 0, len(slice))
	for _, instance := range slice {
		if f(instance) {
			out = append(out, instance)
		}
	}

	return UserSlice(out)
}

