package examples

/* generated by slices (github.com/schigh/slices).  do not edit. */
/* gen date: Wed, 05 Sep 2018 18:06:13 -0400 */

// UserPtrSlice aliases []*User
type UserPtrSlice []*User

// Value returns the wrapped User slice
func (slice UserPtrSlice) Value() []*User {
	return []*User(slice)
}

// Map applies a function to every User in the slice.  This function will mutate the slice in place
func (slice UserPtrSlice) Map(f func(*User) *User) {
	for i := 0; i < len(slice); i++ {
		slice[i] = f(slice[i])
	}
}

// Filter evaluates every element in the slice, and returns all User
// instances where the eval function returns true
func (slice UserPtrSlice) Filter(f func(*User) bool) UserPtrSlice {
	out := make([]*User, 0, len(slice))
	for i := 0; i < len(slice); i++ {
		if f(slice[i]) {
			out = append(out, slice[i])
		}
	}

	return UserPtrSlice(out)
}

// Each applies a function to every User in the slice.
func (slice UserPtrSlice) Each(f func(*User)) {
	for i := 0; i < len(slice); i++ {
		f(slice[i])
	}
}

// TryEach applies a function to every User in the slice,
// and returns the index of the element that caused the first error, and the error itself.
// If every member of the slice returns nil, this function will return (-1, nil)
// The iteration will halt on the first error encountered and return it.
func (slice UserPtrSlice) TryEach(f func(*User) error) (int, error) {
	for i := 0; i < len(slice); i++ {
		if err := f(slice[i]); err != nil {
			return i, err
		}
	}

	return -1, nil
}

// IfEach applies a function to every User in the slice,
// and returns the index of the element that caused the function to return false.
// If every member of the slice evaluates to true, this function will return (-1, true)
// The iteration will halt on the first false return from the function.
func (slice UserPtrSlice) IfEach(f func(*User) bool) (int, bool) {
	for i := 0; i < len(slice); i++ {
		if !f(slice[i]) {
			return i, false
		}
	}

	return -1, true
}
